apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vaultwarden
labels:
  - pairs:
      app.kubernetes.io/name: vaultwarden
      app.kubernetes.io/part-of: k8s-gitops-portfolio
    includeSelectors: true
resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - networkpolicy.yaml
