---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAw1LM0jkhTwgRnqjuJFtCA7GPIFmI+Q7S518xisHKKQVXMyNHsArxFJyVGjacaXhSx1eMfzAoy54s2SH5Ha3uZtYhFDgmI5RELICGX25zuTBangS2Oj7t1qxW5C0o8wvnTEiGvv8EoS/QrxnkeQp8vJj2Wb6FxArKMAgmz1AgxmDxvMdrUHZq5b+OI/KMbsHI87AwStwDHM2LDwNkQv6dYOmWTrwvASe9/l95d9UAUx+QKzvlRvPDKETLNBd26dNc/9LpWUDXx/ppPs+QGuAJ44hja/KEZls4wAKV5sCC+6D3kuc0pTaTS3sjM29ioUMcrdvLowYPFhPZwU7DW4vgs2Y3AW5m2wdfM6HiNOXboonFI9XFDnOw6aNPnND+lNReegqIWoqXXhohooEJDulqVOSCMyTyMlDQx6VdT2Kh77ZswEgdJYxuVSisuJxO4a9nKcOfZ7FoneCgqeTQBHA8ASLDqAVtYo97BpoA7vfh99/5gTGDiVF4UbKlMaw2npnD9w/SqlBvsm5cr7ok70quswNS2qMocutrz14BTsrGyJ2xvc1akTHydPxEi10MJaneTo33lV9i9J7L/vlrTfp7HMHCBg8+gEWHWFijhL7kB5kvAVl37Zst6D19XZTmObeBiYvFn9vzIcnOkqeNM9chL5x6mDQxl6NuO+NsrGNcA7sxsL37anRz5ZSZij3TqCZmvnGEd1AXz9JU0y2erwXHsF0X7zY2oAa8+OLjmN/1V
    admin-user: AgCO9rASx0T8SePQApfWg8J2vMtdvDUXairiqTt8HaWhzmQOL4hWZz49I2HBXacnVoK5eySbE+tx3c4xKY94W88abJ/2Q/IqgOzSu4RGSous+GNkUXbCO/fZrITvHh1j1oVdDDPgDevknWBSMo/uIs7F3ZHBXO0KzrTQultgvDv9hrlH7mDHQCTfIQxaE9Pr8MTurCMEajdpAFZLLFpGVTI2R9kBPvvRJ7OxNJ1Y4svFsFcEVQj+40U8W5iq0MRNYnumjU+xda9MX2130HuOER4K1Uv7D4qYJW770C8vp73KplLjkQoC4fCzgoPteblX1F5K5L2c9dPWSHjC08vv09WTG0Z/80m2IzScW0YfCVz4bznu2LSFlI6TzB2HmSBswcGhJ4jtjy1FPwxPiviCrnZRrsL9EWc/yyrAAF+RQUxT9cwFNI1dFOGv1WYI8QrZLLDN0FsyDzEKtGPwKz8dkYz6XC85UrmknVk5V8b/slTKOv+6e4HJ1jbjlFudMPMXaZ5vgGFi0TUBxUug+8BdV9591MI2UYqEuTYROMQohn8XyA2D8UkVxu5BvbiXmMaz9xTTIDQt8WIimIzvmrhe3oAhFFuB/9tCOmc31h5JeB5vBCvv5xnQ8t3eT9Kmz31MRAlXwFoAySRumlBug4zVNk8L8oPaBQJh7svOPNv4Qwz90T9c6QFMOYJHyHyqvEHf2WtCibYkfg==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
