---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kuma-admin
  namespace: uptime-kuma
spec:
  encryptedData:
    password: AgCCl5BSKqH3AzRbfSCGN4RQ0yZdOzPcsFGCQXFtx0Nb2336n5yfPeM/Or+gSxVSvSScyiMTMORvGWMCO0WnCEPD7jy8jxxnswKCpcgZo1oeozDsdqa+cIWsO7tR0b+xNaJt1D/YM2DPjw2gGirYGdz9smRvKtO9DPlBJ9aJV12s5DW4TElH8bpruFuL2r8WgU0uiZ8ZjZq2rctoOvEKjOYQ6PLJEi5zqLz8YiEF0y7xmdNEbjFvUu0cK/CBOMf+CkKPzQI3KeWxNRsNGzqByxTtKMYQqXtDEwhTVypdhIXmh94N4BrUujxuDu82lSQVVG9HHSlj4Ci64Fc1rFmY5KyU976FqyekGuimkTfLApe8Df58kxXDtXWmSd2xG7j/CIFISylEcSbCousIStcE+3t6UsJVxxWMmze1te9o+Ry90a4u2yKefMVqBunX1D7zLfsws9Fc8GYuSph0ZdF/xlSYnAmL3xkW2hAPjj7q+H9r5ls3pqKPLvinH84j9fC9el1KSmsYk8mKIFAQa6KXtYzP6xryG7B9GyNAXPzcvTZkYy3M2GPZxpJMiVeu2GbLx39iPQTHrvLZ7riO2ga4JVN3aLtpVYXXBRWC5SuOp16o/vjKpadtwiIPALl547kGzi4raskkEvLnFYVwVnrRKuWBWAmDMtsta4tb+vQz1KfyT6S4gfUpIvuDCqCKmQKaIePBX29bMdiUwJ4lE/cdNVzAx2uGKerajZruof7CnMgUTw==
  template:
    metadata:
      name: kuma-admin
      namespace: uptime-kuma
