apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.revision }}
    path: apps/vaultwarden
  destination:
    server: https://kubernetes.default.svc
    namespace: vaultwarden
  {{- include "platform.syncPolicy" (dict "options" (list "CreateNamespace=true") "labels" (dict "pod-security.kubernetes.io/enforce" "restricted")) | nindent 2 }}
